collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2297872
color:
  saturation: 0.0106383
  brandStrength: 0.293617
  lightness: 0.6
  brandColors:
    - '#000000'
    - '#534231'
    - '#92897F'
    - '#BDB3A3'
    - '#FFFFFC'
  rhythmicContrast: 0.2829787
layout_spectrum: 0.2
name: Justin
